# Generated by Django 3.2.7 on 2021-12-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('dirname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
    ]
